unleash:
    url: http://localhost:4242/api
    apiKey: "*:development.da33883b2b2be02c5648ac624a1f50922cbc5893c2e6de5b9f57298d"
    appname: "Java-Spring-Boot-example"
spring:
  devtools:
    restart:
      enabled: true
